package com.Crudsajod.model;
// Importing JPA annotations for entity mapping

import jakarta.persistence.Entity; // Marks this class as a JPA entity
import jakarta.persistence.GeneratedValue;  // Used to auto-generate primary key values
import jakarta.persistence.GenerationType;  // Defines strategies for primary key generation
import jakarta.persistence.Id;  // Marks a field as the primary key
import jakarta.persistence.Table;  // Specifies the database table name


// Importing validation constraint
import jakarta.validation.constraints.NotBlank;

// Lombok annotations to reduce boilerplate code
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity  // Indicates that this class is a JPA entity
@Data    // Lombok: generates getters, setters, and utility methods automatically
@NoArgsConstructor  // Lombok: generates a no-arguments constructor
@AllArgsConstructor // Lombok: generates a constructor with all fields
@Table(name = "cliente")  // Maps this entity to the "cliente" table in the database

public class Cliente {

    @Id  // Marks 'id' as the primary key
    @GeneratedValue(strategy =  GenerationType.IDENTITY) // Primary key is auto-generated by the database
    private long id; // Unique identifier for each client

    @NotBlank(message = "El name es obligatorio")  // Validation: cannot be null or empty
    private String name;


    private String apellido;
    @NotBlank(message = "El correo es obligatorio")
    private String correo;

    @NotBlank(message = "El teléfono es obligatorio")
    private String telefono ;
    @NotBlank(message = "La direccion es obligatorio")
    private String direccion ;

// Getters and Setters (manually written, even though Lombok generates them automatically)

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getApellido(){
        return apellido;
    }
    public void setApellido(String apellido){
        this.apellido = apellido;
    }

    

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion= direccion;
    }
    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

}
